- action:
  - alias: Turn Off E's Light
    data:
      entity_id: light.ge_14294_inwall_smart_dimmer_level
    service: light.turn_off
  alias: Lights Out
  condition: []
  id: '1510584359005'
  trigger:
  - at: '20:00:00'
    platform: time
- action:
  - alias: Turn Easton Light On
    data:
      brightness: '255'
      entity_id: light.eastonroomlight_level
    service: light.turn_on
  alias: Easton Lights On
  condition:
  - after: 06:00:00
    condition: time
  id: '1511917699473'
  trigger:
  - event_data: {}
    event_type: easton_button_pushed
    platform: event
- action:
  - alias: Advanced Set Brightness
    service: light.turn_on
    data_template:
      entity_id: light.masterbathlight_level
      brightness: >
        {%- if now().strftime('%H')| int >= 23 %}
          65
        {%- elif now().strftime('%H')| int >= 22 %}
          137
        {%- elif now().strftime('%H')| int < 7 %}
          45
        {%- endif %}
  alias: Bathroom Night Level
  condition: []
  id: '1512265968551'
  trigger:
  - entity_id: light.masterbathlight_level
    from: 'off'
    platform: state
    to: 'on'
